/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuloIdRouteImport } from './routes/modulo.$id'
import { Route as ApiPublicAdminResponsesRouteImport } from './routes/api/public/admin/responses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloIdRoute = ModuloIdRouteImport.update({
  id: '/modulo/$id',
  path: '/modulo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminResponsesRoute = ApiPublicAdminResponsesRouteImport.update({
  id: '/api/public/admin/responses',
  path: '/api/public/admin/responses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modulo/$id': typeof ModuloIdRoute
  '/api/public/admin/responses': typeof ApiPublicAdminResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modulo/$id': typeof ModuloIdRoute
  '/api/public/admin/responses': typeof ApiPublicAdminResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modulo/$id': typeof ModuloIdRoute
  '/api/public/admin/responses': typeof ApiPublicAdminResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modulo/$id' | '/api/public/admin/responses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modulo/$id' | '/api/public/admin/responses'
  id: '__root__' | '/' | '/modulo/$id' | '/api/public/admin/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModuloIdRoute: typeof ModuloIdRoute
  ApiPublicAdminResponsesRoute: typeof ApiPublicAdminResponsesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$id': {
      id: '/modulo/$id'
      path: '/modulo/$id'
      fullPath: '/modulo/$id'
      preLoaderRoute: typeof ModuloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/responses': {
      id: '/api/public/admin/responses'
      path: '/api/public/admin/responses'
      fullPath: '/api/public/admin/responses'
      preLoaderRoute: typeof ApiPublicAdminResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModuloIdRoute: ModuloIdRoute,
  ApiPublicAdminResponsesRoute: ApiPublicAdminResponsesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
